version: "3.8"

services:
  ###################################################
  # Combined backend + Angular frontend service
  ###################################################
  app:
    build:
      context: ./
      target: final
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    ports:
      - "3000:3000" # Accessible at http://localhost:3000
    depends_on:
      - mysql

  ###################################################
  # MySQL database
  ###################################################
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    volumes:
      - todo-mysql-data:/var/lib/mysql

  ###################################################
  # phpMyAdmin for MySQL
  ###################################################
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"  # Accessible at http://localhost:8080

volumes:
  todo-mysql-data: